generator_kind: fixed_no_rand #fixed 

mask_generator_kwargs:


max_masks_per_image: 1

cropping:
  out_min_size: 180
  handle_small_mode: upscale
  out_square_crop: False
  crop_min_overlap: 1

max_tamper_area: 1.0
